backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: /assets

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home Page'
        name: 'home'
        fields:
          - {
              label: 'Layout',
              name: 'layout',
              widget: 'hidden',
              default: 'home',
            }
          - {
              label: Headshots,
              name: headshots,
              widget: list,
              fields: [{ label: 'Images', name: 'path', widget: 'image' }],
            }
      - file: 'src/pages/about/index.md'
        label: 'About Page'
        name: 'about'
        fields:
          - {
              label: 'Layout',
              name: 'layout',
              widget: 'hidden',
              default: 'about',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'About Page Headshot', name: 'image', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }